### ISSUE TITLE
What expectation library is being used here?

### ISSUE THREAD

**Issue by mLuby** [wallabyjs/wallaby-webpack-es6-react#1]
I can't find where the global `expect` function is coming from—chai or jasmine somewhere?

**Comment by ArtemGovorov** [comment]
Yes, from jasmine. Wallaby for browser is using jasmine by default and jasmine comes with built-in expectation framework. If you [set it to mocha](http://wallabyjs.com/docs/config/overview.html#testing-framework-setting), you'll need to use chai or other assertion library of your choice.

**Comment by mLuby** [comment]
Good to know—thanks!
