### ISSUE TITLE
Test run failure: file src/Label.jsx has invalid syntax

### ISSUE THREAD

**Issue by kennethlynne** [wallabyjs/wallaby-webpack-es6-react#2]
Got this from a clean clone + npm i + run wallaby just now

**Comment by ArtemGovorov** [comment]
Tried from a clean clone and can't reproduce the issue. Tried on OSX and Windows 8, in WebStorm, Atom, VS Code. What editor are you using and what wallaby core version does it have installed?

The error looks like if `.babelrc` is not loaded for some reason. To verify the assumption, try changing `compilers` section as follows:

``` javascript
    compilers: {
      '**/*.js*': wallaby.compilers.babel({ "presets": ["es2015", "react"] })
    },
```

**Comment by kennethlynne** [comment]
Webstorm on mac, the issue is most certainly on my machine only then, I will figure it out! Thanks! :)

**Comment by anbiniyar** [comment]
I am not sure the exact issues here, but I was able to coax wallaby into working by "touch"-ing all the files under the folder. Here is the command that I ran. I can confirm this is definitely machine specific.

`find . -exec touch {} \;`
