### ISSUE TITLE
Supported for React 16.

### ISSUE THREAD

**Issue by garrettmac** [wallabyjs/wallaby-webpack-es6-react#4]
please. I paid for this.

**Comment by ArtemGovorov** [comment]
Updated the sample to React 16. 

Note that if you are using `create-react-app` or Jest as your testing framework, then you don't need the webpack configuration and may use configuration samples from [here](https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app) or [here](https://wallabyjs.com/docs/integration/jest.html).

**Comment by garrettmac** [comment]
thank you, sorry if my note was brut
